Replace the lowrisc GPIO with the GPIO from PULP group
esl-epfl/x-heep pull request #183
Opened 2022-12-09 15:11 UTC by Xinhu-L

This is the draft pr which replace the lowrisc GPIO with the GPIO from PULP group, the driver of the new GPIO is also added.

2022-12-09 19:51 UTC, davideschiavone commented
thanks @Xinhu-L well done and very much appreciated, I will test this soon, just one question,  does it make sense to remove the lowrisc GPIOs?

2022-12-09 20:19 UTC, Xinhu-L commented
> 

I think it make sense to do so, I remove the dependency in the core file but I didn't remove it from this repos, I think it should be fine

2022-12-09 20:19 UTC, Xinhu-L commented
> 
I think it makes sense to do so, I remove the dependency in the core file but I didn't remove it from this repos, I think it should be fine

2022-12-11 15:42 UTC, davideschiavone commented
thanks, I left you some comments.

In addition, it does not compile with verilator

2022-12-11 17:13 UTC, Xinhu-L commented
Could you please tell me where are the comments, cause I don't know where to find them... 
As for the Verilator, I am afraid that I can not tell the reason as all I have done is only based on ASIC simulation on Questasim... Other environments might need further modification to be supported.

2022-12-11 17:54 UTC, davideschiavone requested changes

2022-12-11 18:20 UTC, davideschiavone commented
> Could you please tell me where are the comments, cause I don't know where to find them... As for the Verilator, I am afraid that I can not tell the reason as all I have done is only based on ASIC simulation on Questasim... Other environments might need further modification to be supported.

now the comments should be OK. For verilator ok, I will take care

2022-12-11 18:44 UTC, Xinhu-L commented on hw/core-v-mini-mcu/ao_peripheral_subsystem.sv
> +  gpio #(
I don't think the number of ports can be changed by setting a parameter here, the number of ports is changed by the Makefile command which regenerates all the GPIO .sv files once you reset the port number. However, the port number of these two GPIO modules will always be the same. To make the two GPIO in ao_peripheral_subsystem and peripheral_subsystem have different ports, the only way I can get now is to have two GPIO modules with 24 ports and 8 ports respectively... otherwise Manuel might have some solution cause he is the designer of this GPIO module ;)

2022-12-11 18:52 UTC, Xinhu-L commented on hw/vendor/pulp_platform_gpio/hal/gpio_hal.h
> +#endif
To be honest, I have no idea why it is called _hal, either... But it should be fine if you change it and also other related files : )

2022-12-11 18:59 UTC, Xinhu-L commented on hw/vendor/pulp_platform_gpio/gpio_regs.hjson
> +{
This GPIO also uses the reg_interface regtool.py from lowrisc, I don't see the differences between these two scripts, so it should be OK if you want to generate it with the current reg_interface regtool.py script, but might need some changes on the Makefile commands

2022-12-11 19:00 UTC, Xinhu-L commented
> > Could you please tell me where are the comments, cause I don't know where to find them... As for the Verilator, I am afraid that I can not tell the reason as all I have done is only based on ASIC simulation on Questasim... Other environments might need further modification to be supported.
> 
> now the comments should be OK. For verilator ok, I will take care

Thanks for that! 😄

2022-12-13 07:34 UTC, merged