Clock-gating of peripheral subsystem and memory banks
esl-epfl/x-heep pull request #187
Opened 2022-12-13 21:36 UTC by Sawii00

- Implementation of clockgating of the PERIPH domain and RAM banks by setting the specified bits within the power_manager's registers. 
- Implementation of a simple C test to verify the correct gating.

2022-12-14 19:01 UTC, simone-machetti commented on hw/core-v-mini-mcu/memory_subsystem.sv
> +        .test_en_i(0),
- Complement the clk_gate_en_i[i] signal in order to respect the cell's polarity (when en_i is 0, the clock is disabled).
- Substitute 0 with 1'b0.

2022-12-14 19:02 UTC, simone-machetti commented on hw/core-v-mini-mcu/peripheral_subsystem.sv
> +      .test_en_i(0),
- Complement the clk_gate_en_i signal in order to respect the cell's polarity (when en_i is 0, the clock is disabled).
- Substitute 0 with 1'b0.

2022-12-14 19:04 UTC, simone-machetti commented on sw/applications/example_clock_gating/example_clock_gating.c
> +    for(uint32_t i = 1; i < MEMORY_BANKS; ++i)
Start from memory bank 2 (i=2).

2022-12-14 19:04 UTC, simone-machetti commented on sw/applications/example_clock_gating/example_clock_gating.c
> +    for(uint32_t i = 1; i < MEMORY_BANKS; ++i)
Start from memory bank 2 (i=2).

2022-12-14 19:23 UTC, simone-machetti commented
Add this Verilator directive at the beginning of the file hw/core-v-mini-mcu/memory_subsystem.sv under the already existing one:

/* verilator lint_off MULTIDRIVEN */

2022-12-14 19:25 UTC, simone-machetti commented
Add this Verilator directive at the beginning of this file hw/vendor/pulp_platform_tech_cells_generic/src/rtl/tc_clk.sv with a patch (we can see together how to do it):

/* verilator lint_off UNUSED */

2022-12-15 15:30 UTC, davideschiavone requested changes

2022-12-16 10:18 UTC, Sawii00 commented on hw/vendor/pulp_platform_tech_cells_generic/src/deprecated/pad_functional.sv
> -  `ifndef VERILATOR
I have not directly touched those files. Re-vendoring has changed them I believe.

2022-12-16 10:18 UTC, Sawii00 commented on hw/vendor/pulp_platform_tech_cells_generic/src/deprecated/pad_functional.sv
> +endmodule
Same as above.

2022-12-16 12:35 UTC, merged