add PDM2PCM peripheral
esl-epfl/x-heep pull request #192
Opened 2023-01-09 12:26 UTC by grinningmosfet

2023-01-26 20:15 UTC, davideschiavone requested changes

2023-01-26 20:15 UTC, davideschiavone commented on hw/ip/pdm2pcm/rtl/fir.sv
> +    parameter  WIDTH,
please add everywhere default parameter values

2023-01-26 20:15 UTC, davideschiavone commented on hw/ip/pdm2pcm/rtl/pdm2pcm.sv
> +      .data_i({{14{1'b0}}, pcm_o}),
why pushing 14b equal to 0? can't you add those 14b at the pop side so that you do not waste flip flops?

2023-01-26 21:32 UTC, grinningmosfet commented on hw/ip/pdm2pcm/rtl/pdm2pcm.sv
> +      .data_i({{14{1'b0}}, pcm_o}),
I need to check the FIFO source code/documentation for a width parameter. I thought that the width was fixed at 32 bits, but it may actually be the default value of a parameter.

2023-01-26 21:32 UTC, grinningmosfet commented on hw/ip/pdm2pcm/rtl/fir.sv
> +    parameter  WIDTH,
I'll do this.

2023-01-26 21:36 UTC, grinningmosfet commented on hw/ip/pdm2pcm/rtl/pdm2pcm.sv
> +      .data_i({{14{1'b0}}, pcm_o}),
```
module fifo_v3 #(
    parameter bit          FALL_THROUGH = 1'b0, // fifo is in fall-through mode
    parameter int unsigned DATA_WIDTH   = 32,   // default data width if the fifo is of type logic
    parameter int unsigned DEPTH        = 8,    // depth can be arbitrary from 0 to 2**32
)
```
Yes, it's a default parameter. I'll fix it at the width of the datapath (18 bits) and do the necessary adaptations.

2023-01-27 08:34 UTC, davideschiavone commented on hw/ip/pdm2pcm/rtl/pdm2pcm.sv
> +      .data_i({{14{1'b0}}, pcm_o}),
well, if you push (for example) 4 bits only, and then when you pop you extend the popped value to 18b, wouldn't this mean having (18-4)*FIFO_DEPTH fewer flip flops?

Theoretically, the synthesizer will recognize that those are constant 0s are removing them - but it is a better design practice to design saving area wherever possible IMO

2023-01-27 08:36 UTC, davideschiavone requested changes

2023-01-27 08:36 UTC, davideschiavone commented on hw/ip/pdm2pcm/rtl/pdm2pcm.sv
> +  logic                                        pcm_data_valid_o;
this is not an output, please remove `_o` from here and wherever else :) same in case you have internal signals named `_i` as they were inputs

2023-04-04 09:16 UTC, merged