Add pynq-z2 board files
esl-epfl/x-heep pull request #212
Opened 2023-03-02 13:52 UTC by davidmallasen

Hardcode the path to the pynq-z2 board files to avoid driver issues. However, even if the hello world still works on the FPGA, there are a few warnings arising when synthesizing. I'm marking the pull request as draft until we can figure out what these warnings are.

2023-03-09 12:54 UTC, davideschiavone requested changes
can you also pls remove from the vendor folder the pynq image?

2023-03-09 13:07 UTC, davidmallasen commented on hw/fpga/board_files/vendor/esl_epfl_pynq_z2_board_files.lock.hjson
> +// Copyright lowRISC contributors.
This is written automatically by the script in `x-heep/util/vendor.py`.

2023-03-09 13:08 UTC, davidmallasen commented on hw/fpga/board_files/vendor/esl_epfl_pynq_z2_board_files.vendor.hjson
> +// Copyright 2023 OpenHW Group
True, my bad

2023-03-09 13:13 UTC, davidmallasen commented
I updated with your comments. The image was there because it appears when you open the project directly in Vivado, but I guess it is not strictly needed.

2023-03-09 17:47 UTC, JoseCalero commented
I think this can be merged @davideschiavone :)

2023-03-13 17:27 UTC, JoseCalero commented
@davideschiavone tested w/ fpga using hello w. and freertos apps

2023-03-13 17:31 UTC, merged