DMA HAL
esl-epfl/x-heep pull request #219
Opened 2023-03-09 14:08 UTC by JuanSapriza

# The HAL for the DMA. 
The DMA is the module that can perform memory transfers with minimal CPU interaction, freeing it to perform other tasks/go to sleep. 
Our DMA is capable to make memory transactions from memory to memory, from memory to a peripheral, and from a peripheral to memory. Peripheral to peripheral transactions are not supported. 
Right now, two peripheral interfaces exist: a general purpose SPI and an SPI connected to a flash memory. 
In previous work (hardware included), the name for this peripherals was hardcoded, yet in the implementation of this HAL they are treated in a more abstract way to allow  incorporating new interfaces with the least possible changed needed in the HAL.

## Some definitions
### Transaction
A transaction is an operation to be performed by the DMA. It implies copying bytes from a source pointer into a destination pointer. The transaction configuration can be loaded into the DMA registers once it has been cross-checked and it only starts when the size of the transaction is written in its corresponding register. The transaction is finished once the DMA has sent all its bytes (which not necessarily means they have been received by the final destination).  

### Source and destination
Sources and destinations are the two pointers that will exchange data. Bytes will be copied from the source and into the destination address. 

### Data type
The DMA allows for transactions every 1, 2 or 4 Bytes (Byte, Half Word and Word respectively). The size in bytes of the chosen data type is named 'data unit'. For example, 16 bytes can be 16 data units if the data type is Byte, but 8 data units if the data type is Half Word. 

### Increment
In the case that source and/or destination data are not to be consecutively read/written, a certain increment can be defined. 
For instance, If you have an array of 4-bytes words, but only want to copy the first 2 bytes of each word, you could define the transaction with a Data Type of Half Word and an increment of 2 data units in the source, and 1 data unit in the destination. This way, after each read operation the DMA will increment the read pointer in 4 bytes (2 data units), but the write pointer by only 2 bytes.    

### Alignment
When doing transactions with Bytes, the DMA can read/write from any pointer. However, if the Data Type is larger, words should be aligned so the DMA can make a read/write an affect only the chosen bytes. If a Word or Half Word's pointer is not a multiple of 4 or 2 (respectively), the pointer is "misaligned". In some cases the DMA HAL can overcome this problem reducing the data type (which will reflect on an efficiency loss).  

### Environment
An environment is a region of memory that can optionally be defined by the user to let the HAL know that it can read/write from that region. It is useful to make sure the DMA will not affect reserved memory regions.   
Right now, read and write permissions are not supported by environments, meaning that if it is defined, the DMA will be able to read AND write in it.

### Semaphore
If the source or destination pointer is a peripheral, there are lines connecting the peripheral and the DMA that can be used to control the data flow. This lines are named semaphores as they allow/stop the DMA from sending or reading data. Environments and semaphores cannot coexist. 

### Target
A target is either a region of memory or a peripheral to which the DMA will be able to read or write. When targets are pointing to memory, they can be assigned an environment to make sure that they will comply with memory restrictions. 
Targets include a pointer (a point in the memory, or the Rx/Tx buffer in case of peripherals), a size to be copied (if its going to be used as a source), a data type and an increment. Optionally, they can also include a environment to which they belong.   

### Configuration flags 
During the creation or configuration of environments, targets or transactions, there could be inconsistencies or threatening situations (like writing outside the boundaries of a defined region). To provide the user with information about this potentially harmful situations, configuration flags are set while creating each of these entities. They can be unmasked and checked. 
In some cases, when the threat is too risky, a crucial error might be raised and the operation of the configuration is halted. 
If senseless configurations are input to functions, assertions may halt the whole program. This is reserved for extreme situations that mean the program was not properly coded (e.g. a semaphore value that is not among the available ones is passed). 

## Usage
The basic operation of the DMA HAL follows these steps.
* Creating a target
* Creating another target
* Creating a transaction passing one of the targets as source and the other as a destination
* Load the transaction into the DMA 
* Launch the transaction
* Wait for the transaction to be finished. 

Optionally, one or two environments can be created for the targets. The following possibilities exist: 
* Both targets point to memory, 
  * but they dont use an environment
  * one of them uses an environment
  * they both use environments and
    * they are the same
    *  they are different
* Only one of the targets points to memory, 
  * it uses an environment
  *  it doesnt use an environment 

Once the transaction is created, it can be loaded many times. Once its loaded, it can be launched many times. Targets can be used by more than one transaction, both as source or destination. 

## Special cares

There are a number of problems that can be found while configuring a transaction, and the DMA HAL should be able to detect them and warn the user via configuration flags. Please add as comments any other special case found during testing that should be considered.

### Misalignments
If a misalignment is detected, the HAL should warn the user. If it can fix it by using a smaller data type, it should also allow the user go for this option. 

### Discontinuity 
When the increment is larger than the data unit, this may bring trouble. In the case of misalignments, it could be impossible for the DMA to perform the requested operation. A crucial error should be raised and no operation should be allowed. 

### Overflows
Going beyond the boundaries of an environment cannot only be detected during the creation of a target (noticing that the requested pointer + size will exceed the environments' space), but can be a consequence of the combination of targets. For example, both targets can be well inside their environments, but that the choice of copy size and increment make it impossible to copy into the destination without going outbounds. 

## Overridings
The source and destination could be such that while writing the DMA ends up overriding what its reading. This should not happen. However, this is not yet covered as its a complex situation that could be interesting to some applications (like shifting information inside a buffer). Further work is needed in this matter.  

### Inconsistencies
Some configurations are not compatible. For example, it would make no sense to have an increment if the target is a peripheral. Some of these inconsistencies are treated. Some are yet to be discussed.

2023-03-09 14:40 UTC, davideschiavone requested changes
util pycache should not be pushed, maybe better to add in ignore, for what concern the HW, you should modify the core_v_mini_mcu.sv.tpl and not the sv file directly, as this is generated - the rest I leave it to @JoseCalero

2023-03-09 14:49 UTC, JuanSapriza commented
> util pycache should not be pushed, maybe better to add in ignore, for what concern the HW, you should modify the core_v_mini_mcu.sv.tpl and not the sv file directly, as this is generated - the rest I leave it to JoseCalero

Hmmm... I didn't *knowingly* modified those files. I will double check and try to leave those files out of the PR, because I see my .vscode folder got pushed as well and I have it untracked.

2023-03-09 15:06 UTC, JuanSapriza commented
This should be better. 
I untracked some undesired files (didnt add them to the gitignore because they are specific to my IDE). 
I reverted the changes done in hw and other files not DMA-related.

2023-03-09 15:22 UTC, JoseCalero commented
I will review it as soon as it is not a draft :)

2023-03-10 15:02 UTC, JuanSapriza commented
I leave here the comments we just discussed with @JoseCalero and @StefanoAlbini96

## Documentation Format 
* Adjust comments and function arguments so that everything fits inside the A4 limits
* Fix consistencies in use of white spaces
* Add a second * on comments that are to be included in the documentation
* Divide sections of code with comment blocks and not line comments

## Documentation Content
* Remove unnecessary @ToDo's and fix wrong comments (j_dma, __undef being default)
* Change image: targets are pointers and not regions, this is confusing.

## Code Format
* Divide large _if's_  into local (if-wise) variables.

## Code Content
* For writing full registers, directly write on the *_struct
* To improve function arguments size, usability and avoid passing so many arguments, transform them into a struct. 
* Use a return value and define a default return value. 
* Set the whole _struct to 0 to prevent undesired operations from being launched. 
* Add a define for the masking of the address (magic 3).

## Other things
* Compare code size with and without _static_ before _inline_.

2023-03-10 15:06 UTC, davideschiavone commented
please @JuanSapriza test all the APPs :)

2023-03-10 18:38 UTC, JuanSapriza commented
> please @JuanSapriza test all the APPs :)

@davideschiavone That is also ongoing.

2023-03-13 14:38 UTC, JuanSapriza commented
In the latest push I: 
* Made most of the required changes. I did not add `ret` values, because he structures' flags were already used where a `ret` would be useful.
* I updated the initial description of this PR:
  * Updated the images
  * Added a `Future Work` section. 
* Made the comparison between `static` and/or `inline`: 
  * `inline` functions need to be declared in a header file [[*]](http://www.greenend.org.uk/rjk/tech/inline.html), so other modules would have access to them. I discarded this as a possibility. 
  * Between `static` and `static inline` declarations there was no size change in the generated binary files. This makes me think that the compiler is not "inline-ing" any of these functions. 
  * I would therefore leave them `static inline` as it is the weakest approach (we do not close the door to inline-ing if later we make some modifications and the compiler decides its the best option). 
* Updated all applications using the DMA. Please note that the non-Flash SPI is not working (even before these changes). You can refer to the section `Future work` of the first comment of this PR.

2023-03-20 14:53 UTC, JuanSapriza commented
We will first include @fimtrey's changes on circularity and the trigger/slot management. 

This will be done through a PR on my fork. I will merge it, test it and update this PR.

2023-03-30 12:29 UTC, JoseCalero commented on sw/device/lib/drivers/dma/dma.c
> +    if( isEnv && ( beforeEnv || afterEnv || (isSize && isOutb) ) )
break this is two conditions at least

2023-04-11 07:51 UTC, JoseCalero commented
Let us know when this is ready for merge consideration :)

2023-04-11 09:39 UTC, JuanSapriza commented
These are the things I have yet to do: 

|Task                 | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | Priority    | Estimated time   |
|---------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------|------------------|
| Slots               |  Check why slots numbered 1,2,4,8 are not working but 1,2,3,4 are (checked with Tim and I can see that in hardware they effectively are correct)                                                                                                                                                                                                                                                                                                                                                                                                                                                   |  High       |  2 h             |
|    Test circular    |                                                                                                                                                                                                                                              Finish testing circular mode with SPI with less than 64 bytes.                                                                                                                                                                                                                                                                                        |   High      | 2 h              |
|      Window         |                                                                                                                                                                                                                                                                                                           Test the window interrupt (require PR of PLIC for this)                                                                                                                                                                                                                                  |    High     |  2 h             |
|     Documentation   | Update the documentation                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |      Medium | 2 h              |
|Weak implementations |                                                                                                                                                                                                                                                                                                                                                                  Update weak implementations to `optimize("O0")`                                                                                                                                                                                   |   Low       |      1 h         |
|       FIC           |                                                                                                                                                                                                                                                                                                                                                                                                                 Merge PR of FIC and remove the implementations from the DMA                                                                                                                        | Low         | 1 h              |
|      White tests        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Repeat all the test I had previously done, updating them to include tests concerning circular mode and window interrupts|       High  |              16 h |

We can discuss if something is missing or if some priorities need to be changed. 
If I dedicated solely to this, it could take a week. 
i will update this comment with my progress. I will change the status of the PR to draft as its clearly not yet ready for merge.

2023-06-02 14:44 UTC, JuanSapriza commented
I leave here below an updated version of the documentation (to be exported to the X-HEEP documentation upon merging), as well as a diagram.  Both are works in progress. 

----

# DMA
The **Direct Memory Access (DMA)** peripheral allows data transfers with reduced CPU interaction. 
It can perform *trasactions* of data between peripherals and memory, or memory-to-memory (as a `memcpy` would). 
The CPU is required to configure the transaction, but once launched it is free to go to sleep, process the incoming data or do anything else. 
 
## The DMA HAL
The DMA **Hardware Abstraction Layer (HAL)** facilitates the configuration of transactions from the users application. Furthermore, it adds an additional layer of safety checks to reduce the risk of faulty memory accesses, data override or infinite loops.  


### Previous Definitions
The implementation of this software layer introduced some concepts that need to be understood in order to make proper use of the DMA's functionalities .

#### Transaction
A transaction is an operation to be performed by the DMA. It implies copying bytes from a source pointer into a destination pointer. The transaction configuration can be loaded into the DMA registers once it has been cross-checked and it only starts when the size of the transaction is written in its corresponding register. The transaction is finished once the DMA has sent all its bytes (which not necessarily means they have been received by the final destination).  
Transactions cannot be stopped once they were launched. 
While a transaction is running, new transactions can be validated, but not launched or loaded into the DMA. 
Transactions can be re-launched automatically in `circular mode`. 
Once the transaction has finished, a status bit is changed (that can be monitored through polling) and a fast interrupt is triggered. 

#### Source and destination
Sources and destinations are the two pointers that will exchange data. Bytes will be copied from the source and into the destination address. 

#### Data type
The DMA allows transactions in chunks of 1, 2 or 4 Bytes (`Byte`, `Half-Word` and `Word` respectively). The size in bytes of the chosen data type is called _data unit_ (usually abreviated as `du`). 
For example, 16 bytes can be 16 data units if the data type is `Byte`, but 8 data units if the data type is `Half Word`. 

#### Increment
In the case that source and/or destination data are not to be consecutively read/written, a certain increment can be defined. 
For instance, if you have an array of 4-bytes-words, but only want to copy the first 2 bytes of each word, you could define the transaction with a data type of half word, an increment of 2 data units in the source, and 1 data unit in the destination. This way, after each read operation the DMA will increment the read pointer in 4 bytes (2 data units), but the write pointer by only 2 bytes.    

#### Alignment
When doing transactions with bytes, the DMA can read/write from any pointer. However, if the data type is larger, words should be aligned so the DMA can perform a read/write operation and affect only the chosen bytes. If a word or half-word's pointer is not a multiple of 4 or 2 (respectively), the pointer is _misaligned_. In some cases the DMA HAL can overcome this problem reducing the data type (which will reflect on an efficiency loss).  

#### Environment
An environment is a region of memory that can optionally be defined by the user to let the HAL know that it is allowed to read/write on that region. It is useful to make sure the DMA will not affect reserved memory regions.   
Right now, read and write permissions are not supported by environments, meaning that if it is defined, the DMA will be able to read AND write on it.

#### Triggers and Slots
If the source or destination pointer is a peripheral, there are lines connecting the peripheral and the DMA that can be used to control the data flow (they behave as _triggers_). These lines are connected to _slots_ on the DMA and they allow/stop the DMA from reading/writing data.

#### Target
A target is either a region of memory or a peripheral to which the DMA will be able to read/write. When targets are pointing to memory, they can be assigned an environment to make sure that they will comply with memory restrictions. 
Targets include a pointer (a point in the memory, or the Rx/Tx buffer in case of peripherals), a size to be copied (if its going to be used as a source), a data type and an increment.

#### Configuration flags 
During the creation or configuration of environments, targets or transactions, there could be inconsistencies or threatening situations (like writing outside the boundaries of a defined region). To provide the user with information about this potentially harmful situations, configuration flags are set while creating each of these entities. They can be unmasked and checked. 
In some cases, when the threat is too risky, a _crucial error_ might be raised and the operation of the configuration is halted. 
If senseless configurations are input to functions, assertions may halt the whole program. This is reserved for extreme situations that mean the program was not properly coded (e.g. a slot value is provided and is not among the available ones). 

#### Transaction modes
To take full advantage of the speed and transaprency of the DMA, a _circular_ mode was implemented. When selected, the DMA will relaunch the exactly same transaction upon finishing. This cycle only stops if by the end of a transaction the _transaction mode_ was changed to _single_ (default). 
The CPU receives a fast interrupt on every transaction finished. 

#### Windows
In order to process information as it arrives, the application can define a _window size_ (smaller than the _transaction size_. Every time the DMA has finished sending that given amount of information will trigger an interrupt through the PLIC. 
> :warning: If the window size is a multiple of the transaction size, upon finishing the transaction there will be first an interrupt for the whole transaction (through the FIC), and then an interrupt for the window (through the PLIC, which is slower). 


#### Checks and Validations
The DMA HAL's interface functions perform two types of checks: 
* **Sanity checks**: Make sure that each individual value passed as an argument is reasonable and belongs to the proper domain. This errors will raise an _assertion_ and, depending on how assertions are managed in the application, may result in the program crashing. 
* **Integrity checks**: Arguments are cross-checked to make sure that they abide by the rules of the DMA. If configurations are incompatible, contradictory, or a risk for the programs integrity, warnings are raised through the _configuration flags_. In some special cases, a _critical error_ can be raised, which blocks the deployment of the configuration into the DMA registers. 

> :warning: Integrity checks can be disabled to speed up configuration time. Do this only if you have previously checked the configuration and are sure it will not cause any trouble.  

Checks and validations are performed during the transactions creation, loading and launching. 

A transaction is validated if it went through the creation-checks without raising critical errors.

#### End events
The DMA consideres a certain amount of bytes to have been transferred once it has sent them. It does not wait for a confirmation from the recipient. When a transaction/window is finished the DMA performs a series of event. These may include:
* Changing its status register.
* Raising a _transaction done_ interrupt.
* Raising a _window done_ interrupt.

The DMA HAL can follow up on these changes or let the application be in charge. For this purpose, three different types of _end events_ are defined: 
* **Polling**: The HAL will disable interrupts from the DMA. The application will need to frequently query the status of the DMA to know when a transaction has finished. 
* **Interrup [...]

2023-06-12 09:41 UTC, JuanSapriza commented
I have finished the documentation. It is supposed to complement the one present in the code. 
Please add any comments/questions you might have so it can be improved. I would like that anyone could read it and be ready to start coding a white test for the DMA.

2023-06-19 15:02 UTC, JuanSapriza commented
In the process of rebasing to compatibilize with #203

2023-06-19 16:12 UTC, JuanSapriza commented
@fimtrey Could you try testing the I2S application? I dont have the hardware to do so. 

Also, we are slowly drifting towards apps that can be tested (to make sure that future changes do not break them). Do you think of any way that we could test this app without requiring the microphone? 
Maybe, for simulation, we could fake the answer of the microphone. 
Any ideas @JoseCalero @davideschiavone ?

2023-06-20 16:22 UTC, JuanSapriza commented
[Here is a spreadsheet](https://docs.google.com/spreadsheets/d/1hXeQu6oHp9lK5JQJ8nYAGD4jo1BzW_Ddz3hJdvgP0zU/edit?usp=sharing) that we can use to analyze all the pathological cases and what is the expected return of the HAL. 
It is incomplete, but its a draft that we could use.

2023-06-21 10:45 UTC, fimtrey commented
> @fimtrey Could you try testing the I2S application? I don't have the hardware to do so.

I do not have the hardware anymore...
If you have the FPGA ready, I may be able to drop by and plug in the microphone. 
 
> Also, we are slowly drifting towards apps that can be tested (to make sure that future changes do not break them). Do you think of any way that we could test this app without requiring the microphone? I noticed that this application needs `MEMORY_BANKS=16`, I guess due to the size of the data buffer which is `#define AUDIO_DATA_NUM 0x18000`. I ran it with just 100 words and 16 batches to test it (so it actually ends some day). Would you say this is a viable configuration to leave as default so we can use to test?

This is a demo example so: if somebody wants to run it, fewer than 8 MEM_BANKS are not really interesting, as you get less than 1 second of audio. I had 2048 but @davideschiavone said to put the max. You can put whatever.

It's stupid to store such big amount of data in RAM but there is no second DMA channel to transfer it to the FLASH... in future there will be better ways and no need for 16 MEM_BANKS. 

For testing I'd stick to the simulation.

> Maybe, for simulation, we could fake the answer of the microphone. Any ideas @JoseCalero @davideschiavone ?

This exist, if you build verilator with the external flag (see [ExternalDevices.md](https://github.com/esl-epfl/x-heep/blob/main/ExternalDevices.md))
```
make verilator-sim FUSESOC_FLAGS="--flag=use_external_device_example"
```

2023-06-21 13:03 UTC, JuanSapriza commented
@JoseCalero I could not mark your requested changes as done. Could you take a look. Instead I re-requested your review (hopefully that resets the fla ^^ )

2023-06-21 13:04 UTC, JuanSapriza commented
> > @fimtrey Could you try testing the I2S application? I don't have the hardware to do so.
> 
> I do not have the hardware anymore... If you have the FPGA ready, I may be able to drop by and plug in the microphone.
> 
> > Also, we are slowly drifting towards apps that can be tested (to make sure that future changes do not break them). Do you think of any way that we could test this app without requiring the microphone? I noticed that this application needs `MEMORY_BANKS=16`, I guess due to the size of the data buffer which is `#define AUDIO_DATA_NUM 0x18000`. I ran it with just 100 words and 16 batches to test it (so it actually ends some day). Would you say this is a viable configuration to leave as default so we can use to test?
> 
> This is a demo example so: if somebody wants to run it, fewer than 8 MEM_BANKS are not really interesting, as you get less than 1 second of audio. I had 2048 but @davideschiavone said to put the max. You can put whatever.
> 
> It's stupid to store such big amount of data in RAM but there is no second DMA channel to transfer it to the FLASH... in future there will be better ways and no need for 16 MEM_BANKS.
> 
> For testing I'd stick to the simulation.
> 
> > Maybe, for simulation, we could fake the answer of the microphone. Any ideas @JoseCalero @davideschiavone ?
> 
> This exist, if you build verilator with the external flag (see [ExternalDevices.md](https://github.com/esl-epfl/x-heep/blob/main/ExternalDevices.md))
> 
> ```
> make verilator-sim FUSESOC_FLAGS="--flag=use_external_device_example"
> ```

Great! Thanks @fimtrey, I will test it and leave a note that it can only be run under those circumstances.

2023-06-22 12:05 UTC, JuanSapriza commented
I will close this PR as there are many differences being shown in the _changed files_ window. The [new PR](https://github.com/esl-epfl/x-heep/pull/317) does not have this issue.

2023-06-22 12:05 UTC, closed without merging