im2col C implementation for performance analysis and DMA verification
esl-epfl/x-heep pull request #478
Opened 2024-04-05 09:24 UTC by TommiTerza

These modifications allow the test, verification and performance analysis of the im2col function, implemented in C code, with the ultimate goal of testing the capabilities of the multichannel DMA.
The python script "verification_script.py" generates a random tensor with configurable channels and dimensions, together with a "golden result" used for the verification of the C code, i.e. the output matrix of the im2col.

2024-04-16 15:24 UTC, TommiTerza commented on sw/applications/example_im2col/im2col_lib.c
> +                printf("\nim_row: %d, im_col: %d", im_row, im_col);
Good idea, w.r.t. the cited example I added PRINT_DEB for debugging purposes

2024-04-16 15:25 UTC, TommiTerza commented on sw/applications/example_im2col/im2col_lib.c
> +    }
Fixed!

2024-04-16 15:25 UTC, TommiTerza commented on sw/applications/example_im2col/im2col_lib.c
> +    return 1;
Yes, it's good practice, fixed

2024-04-16 15:26 UTC, TommiTerza commented on sw/applications/example_im2col/im2colGolden.c
I tried to do it in that way at first but the compiler gives a multiple declaration error that I wasn't able to fix

2024-04-17 17:11 UTC, LuigiGiuffrida98 requested changes
I've executed the code on the pynq-z2 and it works even with the minimal configuration (2 BANKS), after these last updates it can be merged.

@davideschiavone please enable the CI checks on this PR so that we can check either there that everything works.

2024-04-17 17:11 UTC, LuigiGiuffrida98 commented on sw/applications/example_im2col/main.c
> +    PRINTF_TIM("Total number of cycles: [%d]\n\n", cycles);
`.../sw/applications/example_im2col/main.c:51: undefined reference to 'PRINTF_TIM'`

Please, doublecheck the occurrences of `PRINTF_TIM`

2024-04-17 17:11 UTC, LuigiGiuffrida98 commented on sw/applications/example_im2col/im2col_lib.c
> +    PRINTF("%d %d\n", OH_NCHW, OW_NCHW);
Prettyprint this as in line 87

2024-04-22 14:47 UTC, merged