fix riscv_dbg to allow n Harts config
esl-epfl/x-heep pull request #525
Opened 2024-06-10 15:21 UTC by LuisDonatien

Fixed some bugs in pulp_platform_riscv_dbg to allow configuration of multiple harts.

Added lint_off rule to avoid warning.

2024-06-10 17:35 UTC, davideschiavone commented
Hello @LuisDonatien , thanks for your fixes.
It seems that you are fixing the pulp debugger, so you should send your PR to this repository https://github.com/pulp-platform/riscv-dbg maintained by ETH and University of Bologna.

In case the fix was already there, then you should just update the vendor hash commit and revendorize the debugger

2024-06-10 17:50 UTC, LuisDonatien commented
> Hello @LuisDonatien , thanks for your fixes. It seems that you are fixing the pulp debugger, so you should send your PR to this repository https://github.com/pulp-platform/riscv-dbg maintained by ETH and University of Bologna.
> 
> In case the fix was already there, then you should just update the vendor hash commit and revendorize the debugger

Hello @davideschiavone, thanks for the quick response.
I'm going to do the PR to the pulp repo and update the hash when it will be accepted.
I will also update this PR with another commit involving the debug_subsystem.sv to allow multiple harts as well.

2024-06-10 18:40 UTC, davideschiavone commented
Thanks @LuisDonatien , jn the meantime feel free to update the debug subsystem in this PR, you don't need another separate PR in my opinion

2024-06-11 13:55 UTC, LuisDonatien commented
Implemented hartinfo_t initialization vector for multiple hart configuration.

2024-06-11 15:30 UTC, davideschiavone commented
thanks @LuisDonatien , if you patch the pulp debug I can merge it in after testing it - only one remark, NHART should be exposed at the very top level of core_v_mini_mcu, otherwise none can change this parameter - it is fine to not expose it to X-HEEP as X-HEEP itself has one HART by default, and when you extend it you usually use core_v_mini_mcu - can you also do that pls? 

@danivz can help you patch the pulp debugger, or if any of the 2 can do it - reach out to me by email

2024-06-12 13:42 UTC, danivz commented
Patch for vendor done!

2024-06-12 13:49 UTC, LuisDonatien commented
Updated NRHARTS exposed at the top level of core_v_mini_mcu through the EXT_HARTS parameter.

Done.

2024-06-12 13:54 UTC, davideschiavone commented
thanks a lot - it looks great - I will have time next week to test it but most probably I am gonna merge as it is

2024-06-19 07:33 UTC, davideschiavone requested changes

2024-06-19 07:33 UTC, davideschiavone commented on hw/core-v-mini-mcu/core_v_mini_mcu.sv
> +      .debug_core_req_o(debug_req),
hi @LuisDonatien , can we also pls expose the debug_reset_n signal? I am not sure but I think there is one for each hart as well

2024-06-19 10:18 UTC, LuisDonatien commented on hw/core-v-mini-mcu/core_v_mini_mcu.sv
> +      .debug_core_req_o(debug_req),
Hi Davide.

I see that your debug_reset_n signal comes from the ndmreset_o in the dm_obi_top inside the debug_subsystem module.
It is more like a general reset for the whole system except for the debugger itself. I think you are right that it has to be exposed externally as well.

**Additional proposal**
In addition to debug_reset_n signal it would be possible to expose the cpu_subsystem_rst_n signal externally as ext_cpu_subsystem_rst to ensure that external harts access peripherals and bus_system correctly initialized?

I can do the PR and you will review the changes.

2024-06-20 14:52 UTC, davideschiavone commented
@LuisDonatien , I think we need to change also the FPGA wrapper https://github.com/esl-epfl/x-heep/blob/main/hw/fpga/xilinx_core_v_mini_mcu_wrapper.sv otherwise we break the FPGA flow

2024-06-20 15:36 UTC, LuisDonatien commented
> @LuisDonatien , I think we need to change also the FPGA wrapper https://github.com/esl-epfl/x-heep/blob/main/hw/fpga/xilinx_core_v_mini_mcu_wrapper.sv otherwise we break the FPGA flow

@davideschiavone 
Do you mean to expose ext_harts parameters through xheep_system to fpga wrapper parameters?

2024-06-20 16:03 UTC, davideschiavone commented
> > @LuisDonatien , I think we need to change also the FPGA wrapper https://github.com/esl-epfl/x-heep/blob/main/hw/fpga/xilinx_core_v_mini_mcu_wrapper.sv otherwise we break the FPGA flow
> 
> @davideschiavone Do you mean to expose ext_harts parameters through xheep_system to fpga wrapper parameters?

I mean to add the new output pins in the xheep instance of the vivado wrapper, otherwise vivado complains about missing pins

2024-06-27 19:52 UTC, merged