CPU and BUS high-level configuration - resolve partially #35
esl-epfl/x-heep pull request #53
Opened 2022-07-22 13:04 UTC by benoitdenkinger

I created a Makefile for most tools. Now CPU and BUS can be used to specify a different value than the ones in the mcu-cfg.hjson file. I checked everything was working with verilator and questasim.

2022-07-22 13:46 UTC, davideschiavone commented
hi @benoitdenkinger thanks a lot, I will try it out asap, mea while, can you please update the README and DEBUG file ? and also, how can one add the flags to fusesoc like use external device or jtag dpi?

2022-07-22 14:30 UTC, benoitdenkinger commented
Hi @davideschiavone, yes sure. I didn't consider all the different cases, only the main ones. I can move everything to the Makefile and put in the README only the corresponding make command for all the different tools and options.

2022-07-22 14:36 UTC, davideschiavone commented
it probably makes sense to use a make variable "FUSESOC_FLAGS" where make passes to fusesoc

2022-07-25 11:09 UTC, benoitdenkinger commented
I updated the README and the Makefile. I kept the previous instructions (how to compile for the different tools with fusesoc) and added a section related to the Makefile. I also removed the $ sign from the commands to have an easier copy-paste of the commands.

2022-07-26 16:37 UTC, davideschiavone commented
you may want to change also the ExternalDevice.md

2022-07-26 16:45 UTC, davideschiavone requested changes

2022-07-26 16:45 UTC, davideschiavone commented on .gitignore
> +hw/core-v-mini-mcu/include/core_v_mini_mcu_pkg.sv
shouldn't we do the same with SW?

2022-07-26 19:11 UTC, benoitdenkinger commented on .gitignore
> +hw/core-v-mini-mcu/include/core_v_mini_mcu_pkg.sv
Yes, you are right.

2022-07-26 20:33 UTC, benoitdenkinger commented
Simulation with verilator works but not with modelsim. In modelsim, the instruction address loop over the first few bootrom instructions (h0 to h10, it does not jump to <_jump_to_flash>).

2022-07-26 20:46 UTC, davideschiavone commented
> Simulation with verilator works but not with modelsim. In modelsim, the instruction address loop over the first few bootrom instructions (h0 to h10, it does not jump to <_jump_to_flash>).

I still have to write a readme for executing from Flash,  there is an open issued. does modelsim work without the boot from Flash flag?

2022-07-26 20:54 UTC, benoitdenkinger commented
My previous comment was not correct/precise. I didn't try to run from flash so I guess it's normal it does not jump to _jump_to_flash. But it doesn't work for modelsim even without trying to boot from flash

2022-07-26 21:07 UTC, davideschiavone commented
> My previous comment was not correct/precise. I didn't try to run from flash so I guess it's normal it does not jump to _jump_to_flash. But it doesn't work for modelsim even without trying to boot from flash

ok then tomorrow we have a look

2022-07-26 21:11 UTC, davideschiavone commented
this function is probably not called in tb_top.sv

tb_set_exit_loop

whereas it is called in the tb_top.cpp

2022-08-02 04:58 UTC, davideschiavone commented on tb/tb_top.sv
> +    if (JTAG_DPI == 0 || boot_sel == 1) begin
why are we pre-loading when booting from flash?

2022-08-02 04:59 UTC, davideschiavone commented on tb/tb_top.sv
> +    if (JTAG_DPI == 0 || boot_sel == 1) begin
I would say "if(JTAG_DPI == 0 && boot_sel = 0)

2022-08-02 04:59 UTC, davideschiavone commented on tb/tb_top.sv
> +    if (JTAG_DPI == 0 || boot_sel == 1) begin
and else if (boot_sel == 0)

2022-08-02 05:00 UTC, davideschiavone commented on tb/tb_top.sv
> +    end else begin
end else if (boot_sel == 0) begin

2022-08-02 11:23 UTC, davideschiavone commented on tb/tb_top.sv
> +    end else begin
I fix it

2022-08-02 11:23 UTC, merged