fix compilation errors of dma_sdk with ohw compiler
esl-epfl/x-heep pull request #532
Opened 2024-06-18 14:51 UTC by LuigiGiuffrida98

@JuanSapriza @JoseCalero can you please review this PR?

2024-06-18 15:35 UTC, JoseCalero commented
it is OK, but the PR is still on draft mode, why? are we waiting to more changings?

2024-06-18 19:38 UTC, JoseCalero commented
ok, i have been debugging a bit, so far this is the output:

`===================================

    TESTING SINGLE MODE   

===================================

TEST:
Data size: 16
Signed: 0
Source type size: 8-bit
Destination type size: 8-bit
Padding not valid
Dimensionality not valid
tran: 10021     Error!
load: 512       Error!
laun: 512       Error!
...`

As you can see, we have problems when validating the transaction (see [dma_validate_transaction](https://github.com/esl-epfl/x-heep/blob/ea26a6f3ceaf634db3619b15f85b4c817f2d3aeb/sw/device/lib/drivers/dma/dma.c#L327))...
Specifically for the Padding and the dimensionality... @JuanSapriza could you help us debugging this?

2024-06-19 10:52 UTC, LuigiGiuffrida98 commented
Fixed all the issues, some fields of the DMA structures where not properly initialized, now everything is set to 0.
example_dma is now working both with riscv32-unknown and riscv32-corev toolchains.

2024-06-20 09:44 UTC, davideschiavone requested changes

2024-06-20 10:35 UTC, LuigiGiuffrida98 commented on sw/applications/example_dma/main.c
> +    // asm volatile ("ebreak");
Done

2024-06-21 09:55 UTC, JuanSapriza commented
Hello @LuigiGiuffrida98 @JoseCalero Just getting up to speed with all this. 
Is anything needed from my side or is this fixed?

2024-06-21 10:10 UTC, merged