Added timer SDK and its respective example
esl-epfl/x-heep pull request #554
Opened 2024-07-15 08:01 UTC by JuanSapriza

It just measures some stuff and prints the result. I did not add a failure condition. If you have ideas, welcome! 

@davideschiavone @JoseCalero

2024-07-15 08:03 UTC, JuanSapriza commented
Fix #547

2024-07-18 10:05 UTC, JoseCalero approved these changes

2024-07-18 10:05 UTC, davideschiavone requested changes

2024-07-18 10:05 UTC, davideschiavone commented on sw/applications/example_timer_sdk/main.c
> +// File: example_dma_sdk.c
example_timer_sdk

2024-07-18 10:14 UTC, davideschiavone approved these changes

2024-07-18 10:14 UTC, merged