Added and integrated spi_obi_slave peripheral to x-heep
esl-epfl/x-heep pull request #597
Opened 2024-10-28 17:42 UTC by panini02

The obi part is missing the byte enable (be) signal

2024-11-22 17:59 UTC, davideschiavone requested changes

2024-11-22 17:59 UTC, davideschiavone commented on sw/applications/example_spi_obi_slave/main.c
> +      .len        = 4,                     // 4 Bytes
I think that if you want to write N bytes you have to pass to the function N-1, look at the examples

2024-11-22 17:59 UTC, davideschiavone commented on sw/applications/example_spi_obi_slave/main.c
> +        .len        = 1,                    // 1 Byte (The SPI SLAVE IP can only take one CMD byte at a time)
I think that if you want to write N bytes you have to pass to the function N-1, look at the examples

2024-12-10 09:23 UTC, JuanSapriza commented
:+1:

2025-01-10 07:45 UTC, merged